// packages/angular/src/lib/tabs.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  ViewEncapsulation,
} from '@angular/core';
import {
  RdxTabsContentDirective,
  RdxTabsListDirective,
  RdxTabsRootDirective,
  RdxTabsTriggerDirective,
} from '@radix-ng/primitives/tabs';

@Component({
  selector: 'p4-tabs',
  standalone: true,
  imports: [CommonModule, RdxTabsRootDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div
      rdxTabsRoot
      [value]="value"
      [defaultValue]="defaultValue"
      (valueChange)="valueChange.emit($event)"
    >
      <ng-content />
    </div>
  `,
})
export class TabsComponent {
  @Input() defaultValue: string | undefined;
  @Input() value: string | undefined;
  @Output() valueChange = new EventEmitter<string>();
}

@Component({
  selector: 'p4-tabs-list',
  standalone: true,
  imports: [CommonModule, RdxTabsListDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div
      rdxTabsList
      class="inline-flex h-10 items-center justify-center rounded-md bg-neutral-100 p-1 text-neutral-600"
    >
      <ng-content />
    </div>
  `,
})
export class TabsListComponent {}

@Component({
  selector: 'p4-tabs-trigger',
  standalone: true,
  imports: [CommonModule, RdxTabsTriggerDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <button
      rdxTabsTrigger
      [value]="value"
      [disabled]="disabled"
      class="inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-white data-[state=active]:text-neutral-900 data-[state=active]:shadow"
    >
      <ng-content />
    </button>
  `,
})
export class TabsTriggerComponent {
  @Input({ required: true }) value!: string;
  @Input() disabled = false;
}

@Component({
  selector: 'p4-tabs-content',
  standalone: true,
  imports: [CommonModule, RdxTabsContentDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div
      rdxTabsContent
      [value]="value"
      class="mt-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500"
    >
      <ng-content />
    </div>
  `,
})
export class TabsContentComponent {
  @Input({ required: true }) value!: string;
}

// packages/react/src/lib/Tabs.tsx
import { Tabs as RadixTabs } from 'radix-ui';
import {
  forwardRef,
  type ComponentPropsWithoutRef,
  type ElementRef,
} from 'react';

const listClasses =
  'inline-flex h-10 items-center justify-center rounded-md bg-neutral-100 p-1 text-neutral-600';

const triggerClasses =
  'inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-white transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-white data-[state=active]:text-neutral-900 data-[state=active]:shadow';

const contentClasses =
  'mt-2 ring-offset-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500';

export const TabsRoot = RadixTabs.Root;

export const TabsList = forwardRef<
  ElementRef<typeof RadixTabs.List>,
  ComponentPropsWithoutRef<typeof RadixTabs.List>
>(function TabsList({ className, ...rest }, ref) {
  return (
    <RadixTabs.List
      ref={ref}
      className={[listClasses, className].filter(Boolean).join(' ')}
      {...rest}
    />
  );
});

export const TabsTrigger = forwardRef<
  ElementRef<typeof RadixTabs.Trigger>,
  ComponentPropsWithoutRef<typeof RadixTabs.Trigger>
>(function TabsTrigger({ className, ...rest }, ref) {
  return (
    <RadixTabs.Trigger
      ref={ref}
      className={[triggerClasses, className].filter(Boolean).join(' ')}
      {...rest}
    />
  );
});

export const TabsContent = forwardRef<
  ElementRef<typeof RadixTabs.Content>,
  ComponentPropsWithoutRef<typeof RadixTabs.Content>
>(function TabsContent({ className, ...rest }, ref) {
  return (
    <RadixTabs.Content
      ref={ref}
      className={[contentClasses, className].filter(Boolean).join(' ')}
      {...rest}
    />
  );
});

export const Tabs = TabsRoot;
