// packages/vue/src/lib/Tooltip.vue
<script setup lang="ts">
import {
  TooltipProvider,
  TooltipRoot,
  TooltipTrigger,
  TooltipPortal,
  TooltipContent,
} from 'reka-ui';

defineProps<{
  delayDuration?: number;
  side?: 'top' | 'right' | 'bottom' | 'left';
}>();
</script>

<template>
  <TooltipProvider :delay-duration="delayDuration ?? 300">
    <TooltipRoot>
      <TooltipTrigger as-child>
        <slot />
      </TooltipTrigger>
      <TooltipPortal>
        <TooltipContent
          :side="side ?? 'top'"
          :side-offset="4"
          class="z-50 overflow-hidden rounded-md bg-neutral-900 px-3 py-1.5 text-sm text-white shadow-md"
        >
          <slot name="content" />
        </TooltipContent>
      </TooltipPortal>
    </TooltipRoot>
  </TooltipProvider>
</template>

// packages/react/src/lib/Tooltip.tsx
import { Tooltip as RadixTooltip } from 'radix-ui';
import {
  forwardRef,
  type ComponentPropsWithoutRef,
  type ElementRef,
  type ReactNode,
} from 'react';

export const TooltipProvider = RadixTooltip.Provider;
export const TooltipRoot = RadixTooltip.Root;
export const TooltipTrigger = RadixTooltip.Trigger;
export const TooltipPortal = RadixTooltip.Portal;
export const TooltipArrow = RadixTooltip.Arrow;

const contentClasses =
  'z-50 overflow-hidden rounded-md bg-neutral-900 px-3 py-1.5 text-sm text-white shadow-md animate-in fade-in-0 data-[state=closed]:animate-out data-[state=closed]:fade-out-0';

export const TooltipContent = forwardRef<
  ElementRef<typeof RadixTooltip.Content>,
  ComponentPropsWithoutRef<typeof RadixTooltip.Content>
>(function TooltipContent(
  { className, sideOffset = 4, children, ...rest },
  ref,
) {
  const composed = [contentClasses, className].filter(Boolean).join(' ');
  return (
    <RadixTooltip.Content
      ref={ref}
      sideOffset={sideOffset}
      className={composed}
      {...rest}
    >
      {children}
    </RadixTooltip.Content>
  );
});

export interface TooltipProps {
  content: ReactNode;
  children: ReactNode;
  delayDuration?: number;
  side?: 'top' | 'right' | 'bottom' | 'left';
}

export function Tooltip({
  content,
  children,
  delayDuration = 300,
  side = 'top',
}: TooltipProps) {
  return (
    <TooltipProvider delayDuration={delayDuration}>
      <TooltipRoot>
        <TooltipTrigger asChild>{children}</TooltipTrigger>
        <TooltipPortal>
          <TooltipContent side={side}>{content}</TooltipContent>
        </TooltipPortal>
      </TooltipRoot>
    </TooltipProvider>
  );
}
